apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: objdet-test-oct30 
  janus-idp.io/tekton: objdet-test-oct30
  backstage.io/kubernetes-id: objdet-test-oct30
  backstage.io/kubernetes-namespace: rhdh-test 
  app.kubernetes.io/part-of: objdet-test-oct30
resources: 
- application-dev.yaml