apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: objdet-test-oct30
  janus-idp.io/tekton: objdet-test-oct30
  backstage.io/kubernetes-id: objdet-test-oct30
  backstage.io/kubernetes-namespace: rhdh-test 
  app.kubernetes.io/part-of: objdet-test-oct30
resources: 
- initialize-namespace.yaml
- deployment-model-server.yaml
- service-model-server.yaml
- deployment.yaml
- route.yaml
- service.yaml
- model-config.yaml
