apiVersion: batch/v1
kind: Job
metadata:
  name: dsp-clone-job-objdet-test-oct30-gitops
spec:  
  template:         
    metadata:
      name: dsp-clone-job-objdet-test-oct30-gitops
    spec:  
      serviceAccountName: objdet-test-oct30-dsp-job
      containers:
      - name: initialize-dsp
        image: quay.io/redhat-ai-dev/utils:latest
        command:
        - /bin/bash
        - -c
        - |
          NS=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
          oc wait -l statefulset=objdet-test-oct30-notebook --for=condition=ready pod --timeout=300s
          oc exec  StatefulSet/objdet-test-oct30-notebook -- git clone https://github.com/jdubrick-ai/objdet-test-oct30
      restartPolicy: Never